language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install: python setup.py install
script: python setup.py test
deploy:
  provider: pypi
  user: benverbeken
  password:
    secure: HUf8ieLN3B3XAmbyGU44O4HA9kdfYWwnjUOm0dT+REdLVKhwq9JlCZm0NC95/zpia4CW2BpEwbDGgODFetshD4rdOGyO5ktMlop5Occqo8yYa1+/3vwZIBSt/IrY72pocYy0vGMxWlMjFBoNBp70y3XdUx85dNARcRsIRsOgKSKk4MuF37thXT6l5b5YtQBD2/XdeINr+S0As6gUFfRr5IEEQsYcYS4yWdwiFysaDzr01wTL8+obqSRVX5+CntUMqBMbS+ugg5SGyYC4Wv6T5/XP8qc6ONKT3gt1e+d1MGq8bQW0xkzOspT0mHnBgnwR9E463z+5BqhgxYS4FSnCs0ft2iaUcWqsoxQ9mcD39jtAwICdeP8VLYPPRuN7xYJQ6nNxKOz9Njs/2bcfnQdcoNFhmXt3FEJf2ZgavgPo1jH6Sdnmn/AD7gjYj9IIvrFUnYc/WptBmU7/KkSfBPh6Y7qs3Pwn5AodxE6375YaYVQEoq6nj/Ez4SZ6Yi71r+Lb6DvpiK3gnA+MKpTL2bkwBwoDhzUQA1YVX2Uo2Wa5xp+ofdGuvHbjh6JRlNwf0dSM15bjDZs1H8br3/7GHQD2cOIEW6hxx5iwdiCuNKnUxOEfZ5PtYgUjREMDxvKhSu6fXs58qtb74qP8foW7ehyzap+HpcmmJ71JnjlxdEUmBWY=
  on:
    tags: true